# Entry
1
## Start time
05/22/24 11:00
## Purpose
Go over Sprint 1 and plan for Sprint 2.
## Outcomes
- Discussed everyone's indivial progress
- Planned ahead for Sprint 2, creating google doc and deciding on/dividing up tasks
## End time
05/22/24 11:30

# Entry
2
## Start time
05/29/24 11:00
## Purpose
Go over Sprint 2 and plan ahead for Sprint 3. Iron out any concerns or issues.
## Outcomes
- Each shared current state and individual progress
- Worked out issues and clarified uncertainties regarding Sprint 2 work.
- Discussed future work, such as integration of front and back end, data persistence...
- Planned ahead for Sprint 3 (creating doc and finding/dividing up tasks)
## End time
05/29/24 11:30

# Entry
3
## Start time
06/05/24 11:00
## Purpose
Review Sprint 3 progress, figure out any issues and plan goals/tasks for Sprint 4.
## Outcomes
- Each shared current state and individual progress
- Demoed spreadsheet UI and formula passing functionality
- Ironed out issues and clarified uncertainties regarding project completion
- Discussed saving feature and how to implement it
- Made plans for integration of front and back end
- Made plans for project completion by EOW
- Planned out tasks/goals for final sprint
- Discussed collaboration on integration
## End time
06/05/24 11:30

# Entry
4
## Start time
06/06/24 17:30
## Purpose
Touch base on progress/remaining goals and tasks, demo the backend, plan next meeting time.
## Outcomes
- Planned out final integration of work
- Demoed backend
- Decided on data/time for next meeting
## End time
06/06/24 17:55

# Entry
5
## Start time
06/09/24 15:30
## Purpose
Touch base on integration of all seperate components and determine remaining tasks
## Outcomes
- Touched base on current progress
- Discussed test code coverage reports
- Planned next potential meeting
## End time
06/09/24 15:40

# Entry
6
## Start time
06/11/24 10:50
## Purpose
Work on putting everything together
## Outcomes
- Worked on completeing project
- Discussed current issues with code
## End time
06/11/24 11:50
