# Entry
1
## Start time
05/9/24 10:30
## Purpose
Setup project repositories
## Ownership
+156 = 156
## Outcomes
Created repo for project code and for notebooks, sharing with group members.
## End time
05/9/24 10:30


# Entry
2
## Start time
05/14/24 10:30
## Purpose
Started planning project objectives and filling out our SOW.
## Outcomes
Created a basic list of goals for our MVP and added some desirable/additional features
## End time
05/14/24 11:00

# Entry
3
## Start time
05/15/24 9:50
## Purpose
To go over and verify that our SOW is correct and sufficient, amending any issues.
## Outcomes
Recieved feedback on SOW, due diligence on SOW requirements and format.
## End time
05/15/24 10:20

# Entry
4
## Start time
05/16/24 11:30
## Purpose
Prepared and layed out my individual work for sprint 0, including what portoin of code to work on, exactly what needed to be programmed, etc
## Outcomes
Managed to create and layout detailed steps on what I will have to carry out for sprint 0.
## End time
05/15/24 11:45

# Entry
5
## Start time
05/16/24 14:00
## Purpose
Set up/implement the server (SSL, basic endpoints, authentication)
## Commit(s)
Waiting to commit
## Ownership
+467 = 562
## Outcomes
- Set up the project structure with Maven and necessary dependencies.
- Implemented basic authentication using SSL.
- Created endpoints for `register`, `getPublishers`, `createSheet`, `deleteSheet`, `getSheets`.
- Tested functionality with initial tests.
- Set up postman collection for testing API routes.
## End time
05/16/24 16:00

# Entry
6
## Start time
05/22/24 21:00
## Purpose
Push sprint 0, setting up the server
## Commit(s)
https://github.com/silasnevstad/CS4530-Project/commit/a27cf2617d79deeb1e569b0f02ac7abc176cc099
## Ownership
-2 +538 = 1098
## Outcomes
- Reviewed code and tests, making final checks and ensuring everything is in place before pushing.
- Wrote server-architecture.md documenting the server implementation in detail.
- Pushed changes to repo.
## End time
05/22/24 21:30

# Entry
7
## Start time
05/27/24 12:00
## Purpose
Small fixes and optimizations
## Ownership
-2 +6 = 1102
## Outcomes
- Scanned over previous work for optimizations and refactoring
- Optimized a few lines
- Made plan for next session
## End time
05/27/24 12:20

# Entry
8
## Start time
05/29/24 1:35
## Purpose
Sprint 2 goals, implement rest of endpoints w/ testing (updates and subscriptions) and finish pre assigned auth.
## Commit(s)
[Code](https://github.com/silasnevstad/CS4530-Project/commit/2a8ae07559889591a6a8e9f42da4e0251f1f3854)
[Tests](https://github.com/silasnevstad/CS4530-Project/commit/c2fd8e3c426a507f888f6ca6287ec7ee2da73809)
## Ownership
-93 +265 = 1274
-2 +397 = 1669
## Outcomes
- Implemented all remaining endpoints:
  - `POST /api/v1/getUpdatesForSubscription`
  - `POST /api/v1/getUpdatesForPublished`
  - `POST /api/v1/updatePublished`
  - `POST /api/v1/updateSubscription`
- Completed and tested the pre-assigned auth
- Verified and tested services and endpoints using JUnit 5 and Mockito
- Updated design-architecture.md to reflect the current state of the project and testing tools used
- Added new routes to `Postman` collection
## End time
05/27/24 3:45

# Entry
9
## Start time
06/03/24 22:15
## Purpose
Brainstorming/planning data persistence.
## Outcomes
- Decided on using SQL databsae (SQLite)
- Planned out design and changes needed (e.g. tables needed, which functions require updates, etc)
## End time
06/03/24 22:30

# Entry
10
## Start time
06/04/24 17:00
## Purpose
Implement data persistence
## Commit(s)
https://github.com/silasnevstad/CS4530-Project/commit/72679815f2a4f3f621ca7917d25a36054a020cf3
## Ownership
-66 +305 = 1974
## Outcomes
- Setup SQLite database service.
  - Configuring the database URL for connection.
  - Initializing the database with necessary tables (publishers, sheets, updates).
  - Implementing retry logic for database operations to handle potential SQLITE_BUSY errors.
- Refactored the PublisherService to use SQLite for data persistence.
- Combined updates and subscriptions into a single table to streamline update retrieval.
- Modified functions to use SQL queries for data operations.
- Fixed and updated tests to work with the new SQLite setup.
- Ensured tests do not affect the actual production database by using an in-memory database during testing.
- Updated server-architecture.md to reflect changes made for data persistence.
## End time
06/04/24 19:25

# Entry
11
## Start time
06/04/24 19:35
## Purpose
Commit required encrypted keystore and truststore files (needed for server) + add instructions
## Commit(s)
https://github.com/silasnevstad/CS4530-Project/commit/40442949816fb81b7662dd2ef1d105ab11908ddf
https://github.com/silasnevstad/CS4530-Project/commit/c303a02a0eb414ec0b47ee2abba43f122b31faed
https://github.com/silasnevstad/CS4530-Project/commit/ab100b30c9aefd3acf17bc0456faf728060db010
## Ownership
+45 = 2019
## Outcomes
- Encryped and pushed required keystore and truststore files to repo
- Made decryption bash script for easier decryption
- Updated README with setup instructions
## End time
06/04/24 19:50

# Entry
12
## Start time
06/06/24 17:55
## Purpose
Add documentation (including owner tags to files), create more tests for edge cases, restructure into server folder
## Commit(s)
[Restructure](https://github.com/silasnevstad/CS4530-Project/commit/cfb51b5d66bd8bbafe3272c4c1a6babcc8934356)
[Owner Tags](https://github.com/silasnevstad/CS4530-Project/commit/81af78a6e12ef2414b5acea82ebbd1a8654ab6f4)
[Tests + documentation](https://github.com/silasnevstad/CS4530-Project/commit/b92f4d38ddd56d62ab9f7ddd32e6e07ff33650c3)
## Ownership
-18 +26 = 2027
+16 = 2043
-19 +716 = 2740
## Outcomes
- Restructured project structure to include server files in server folder
- Added owner tags to all my files
- Add documentation throughout my code (functions, explainations, etc)
- Added more tests for edge cases specifically
- Added invalid input checks for every endpoint and function (checking if input is invalid)
## End time
06/06/24 19:15

# Entry
13
## Start time
06/07/24 22:00
## Purpose
Test coverage + report
## Outcomes
- Added jacoco plugin
- Experimented with IntelliJ run configurations (to add code coverage)
- Test code coverage
- Found nit bug in controller testing file
  - Looked for fixes
## End time
06/07/24 22:20

# Entry
14
## Start time
06/08/24 14:10
## Purpose
Test coverage + report, fix nit in controller testing code
## Commit(s)
https://github.com/silasnevstad/CS4530-Project/commit/71af15c89760035eae8fd1bb17dc987db7f8b3a2
## Ownership
-19 +716 = 2740
-45 +321 = 3016
## Outcomes
- Fixed nit bug in testing code
- Nit: Prevent invalid Authorization header to avoid having to check against users
- Added more tests to reach 100% coverage
- Completed test code coverage with 100%
## End time
06/08/24 14:50

# Entry
15
## Start time
06/11/24 11:10
## Purpose
Integrate front/back end + Frontend saving/pulling updates functionality + Setup docker files and docker-compose + Restructure app folders/files
## Commit(s)
https://github.com/silasnevstad/CS4530-Project/commit/72839d3e2a35bfbaf9272ffd9abed6892d555894
https://github.com/silasnevstad/CS4530-Project/commit/7432cc3803fe26a02bae304840ad84226814f0ce
## Ownership
-7628 +552 = 3568
-2 +70 = 3636
## Outcomes
- Restructured project directory to seperate front and back end, etc.
- Setup backend service for frontend interaction with server
- Added saving functionality (using timer)
- Added pulling in updates functionality (using timer)
- Setup dockerfiles + docker-compose (incomplete)
- Found problem in backend server, fixed to allow for mutliple updates in one payload (when pushing uploads to server)
  - Added tests to cover new logic
## End time
06/11/24 13:30

# Entry
16
## Start time
06/11/24 21:00
## Purpose
Fix dockerization + differentiate between owners and subscribers + fix client javafx issue
## Commit(s)
https://github.com/silasnevstad/CS4530-Project/commit/3a72a746e4e8da7365127373c15d312ebd6e8285
https://github.com/silasnevstad/CS4530-Project/commit/951cb94e380195be74529fac6657bee12f306e88
## Ownership
-6 +48 = 3678
## Outcomes
- No luck fixing dockerization
- Added functionality to differentiate between owners and subscribers when pushing and pulling updates to the server
## End time
06/11/24 21:30

# Entry
17
## Start time
06/11/24 23:00
## Purpose
Fix cert issues
## Commit(s)
https://github.com/silasnevstad/CS4530-Project/commit/eb37c2819c9f40c854fd534f5b4a444258f69631
https://github.com/silasnevstad/CS4530-Project/commit/ddf21bdf2b541c7f1ab3e9c133ab1132caf5f2d7
https://github.com/silasnevstad/CS4530-Project/commit/42f984c086a1472e91299501ff5bbf122126450d
## Ownership
-8 +18 = 3688
-1 +1 = 3688
-1 +2 = 3689
## Outcomes
- Investigated "can't find valid certificate" error and solved by providing the custom truststore to the command line when running client
- Fixed/Tested saving and getting updates feature
- Updated Makefile to use custom truststore
## End time
06/11/24 23:30

# Entry
18
## Start time
06/12/24 16:30
## Purpose
Finish project: setup transitions from welcome page, sheet select page and spreadsheet view + fix login + fix create sheet + restructure frontend folders
## Commit(s)
https://github.com/silasnevstad/CS4530-Project/commit/65e38c613f9efab0c4844396299afee37ee41423
## Ownership
-683 +1,037 =4043
## Outcomes
- Got most things working (still a few things missing/minor flaws)
- Fixed login page to allow for publisher name (checking auth and registering)
- Updated sheet select page to show sheets in ListView and allow user to open sheets
- Refactored code
- Fixed create sheet problems (reported from group member)
- Restructed/organized frontend folders
- Worked on bonus renaming feature
## End time
06/11/24 20:00

# Entry
19
## Start time
06/13/24 17:45
## Purpose
Setup client with professor's server
## Ownership
=4043
## Outcomes
- Ran into SSL handshake errors
- Tried to get the certificate/certificate chain using WireShark
- Managed to get all certificates and add to truststore but getting same SSL handshake error
## End time
06/11/24 19:20
